/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MusicPrayer;

import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import jaco.mp3.player.MP3Player;

/**
 *
 * @author kartika
 * 
 */
public class PemutarMusik extends javax.swing.JFrame {
    // menyimpan ekstensi file
    String fileExtention;
    // menyimpan posisi audio di jeda
    Long currentFrame;
    Clip clip;

    //Konstruktor untuk menyimpan audio
    AudioInputStream audioInputStream;
    
    static String filePath;
    // Mendefinisikan kelas dari librari jaco
    MP3Player player;
    // Mendefinisikan file lagu
    File songFile;

    /**
     * Creates new form MediaPlayer
     */
    public PemutarMusik() {
        initComponents();
        this.setTitle("MP3 & WAV MEDIA PLAYER");
        // menambahkan metode untuk menjalankan variabel
        player = mp3Player();
    }

    private MP3Player mp3Player() {
        MP3Player mp3Player = new MP3Player();
        return mp3Player;
    }

    public void WavPlayer() throws IOException, UnsupportedAudioFileException, LineUnavailableException {
        // mengisi audio input stream dari lagu  
        audioInputStream
                = AudioSystem.getAudioInputStream(new File(filePath).getAbsoluteFile());
        // clip untuk memainkan wav
        clip = AudioSystem.getClip();

        // membuka audioInputStream ke dalam clip 
        clip.open(audioInputStream);

//        clip.loop(Clip.LOOP_CONTINUOUSLY);
    }

    public void playWav() {
        //fungsi untuk menjalankan file wav
        clip.start();

    }

    public void pauseWav() {
       //fungsi mendapatkan lokasi audio di jeda
        this.currentFrame
                = this.clip.getMicrosecondPosition();
        clip.stop();
    

    }

    public void stopWav() {
       //fungsi menghentikan file wav yang diputar
        currentFrame = 0L;
        clip.stop();
        clip.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stop = new javax.swing.JButton();
        main = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        jeda = new javax.swing.JButton();
        lokasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(86, 112, 247));

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MusicPrayer/thumbnail.png"))); // NOI18N

        stop.setBackground(new java.awt.Color(0, 0, 153));
        stop.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        stop.setText("Stop");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        main.setBackground(new java.awt.Color(204, 0, 204));
        main.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        main.setText("Mainkan");
        main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainActionPerformed(evt);
            }
        });

        cari.setBackground(new java.awt.Color(204, 0, 204));
        cari.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jeda.setBackground(new java.awt.Color(0, 0, 153));
        jeda.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jeda.setText("Jeda");
        jeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jedaActionPerformed(evt);
            }
        });

        lokasi.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jeda, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(main)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lokasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jeda)
                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainActionPerformed
        // TODO add your handling code here:
        //jika file berekstesi wav maka akan menjalankan fungsi play wav
        if (".wav".equals(fileExtention)) {
            playWav();
        //selain itu akan menjalankan pemutar mp3
        } else {
            player.play();
        }

    }//GEN-LAST:event_mainActionPerformed

    private void jedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jedaActionPerformed
        // TODO add your handling code here:
        cari.setEnabled(false);
        if (".wav".equals(fileExtention)) {
            pauseWav();
        } else {
            player.pause();
        }
    }//GEN-LAST:event_jedaActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        if (".wav".equals(fileExtention)) {
            try {
                stopWav();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            player.stop();
        }

    }//GEN-LAST:event_stopActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        File filenya;
        JFileChooser chooser = new JFileChooser("."); //komponen untuk membuka file
        chooser.setFileFilter(new FileNameExtensionFilter(".mp3", ".wav", "mp3", "wav")); //hanya menyaring file wav dan mp3
        int buka_dialog = chooser.showOpenDialog(PemutarMusik.this); //mentriger popup windows
        if (buka_dialog == JFileChooser.APPROVE_OPTION) {
            filenya = chooser.getSelectedFile();
            filePath = filenya.getAbsolutePath();
            String fileName = filenya.getName();
            try {
                fileExtention = fileName.substring(fileName.lastIndexOf("."), fileName.length());
               
                    lokasi.setText(fileName);
                    if (".wav".equals(fileExtention)) {
                        // memasukkan file wav
                        WavPlayer();
                    } else {
                        //menambahkan file mp3 kedalam playlist
                        player.addToPlayList(chooser.getSelectedFile());
                    }
                
            } catch (Exception e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemutarMusik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jeda;
    private javax.swing.JLabel lokasi;
    private javax.swing.JButton main;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
